apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-store<SUFFIX>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-store<SUFFIX>
  template:
    metadata: 
      labels:
        app: bff-store<SUFFIX>
      annotations:
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: bff-store
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /oauth/security-config.json
          name: security-config-bff-store
          subPath: security-config.json
      imagePullSecrets:
      - name: regcred
      tolerations:
      - key: <TOLERATIONS_KEY>
        operator: "Equal"
        value: "True"
      nodeSelector:
        applications: <NODE_AFFINITY>
      volumes:
      - configMap:
          items:
            - key: security-config.json
              path: security-config.json
          name: security-config-bff-store
        name: security-config-bff-store
---
apiVersion: v1
kind: Service
metadata:
  name: bff-store-service
spec:
  selector:
    app: bff-store
