resources:
- resources/bff-store.yaml
- resources/ingress.yaml

namespace: <NAMESPACE>

patchesStrategicMerge:
- config/annotations.yaml
- config/images.yaml
- config/config-map-ref.yaml
- config/local/<BRANCH>/ports.yaml

configMapGenerator:
- name: bff-store-properties-<BRANCH>
  env: config/local/<BRANCH>/bff-store.properties

secretGenerator:
  - name: db-secret
    files:
    - config/local/<BRANCH>/db_creds.txt

#secretGenerator 
generatorOptions:
  disableNameSuffixHash: true
