apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-store<SUFFIX>
spec:
  template:
    metadata:
      annotations:
        gitlab-commit-ref: <GITLAB-COMMIT-REF>
        gitlab-pipeline-ref: <GITLAB-PIPELINE-REF>