apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-store<SUFFIX>
spec:
  template:
    spec:
      containers:
      - name: bff-store
        envFrom:
        - configMapRef:
            name: bff-store-properties-<BRANCH>