apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-store<SUFFIX>
spec:
  template:
    spec:
      containers:
      - name: bff-store
        # TODO: image: <REGISTRY_URL>/bff-store:<VERSION>
        image: springio/gs-spring-boot-docker